services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=tutorialRoot
      - MYSQL_DATABASE=dbAsterisk
      - MYSQL_USER=noms
      - MYSQL_PASSWORD=tutorial
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptutorialRoot"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:

